#!/usr/bin/env bash
# One-command seeded local demo of TrackTub.
#
#   tt-demo         boot local Supabase (if needed) + seed (if empty) + run dev
#   tt-demo reset   wipe + re-apply migrations + re-seed fresh, then run dev
#   tt-demo stop    stop the local stack and revert dev back to prod (.env.local)
#
# Opens at http://localhost:3001 — use the "Local demo" sign-in buttons on /login.
set -euo pipefail

WEB="$(cd "$(dirname "$0")/.." && pwd)"   # apps/web
cd "$WEB"
cmd="${1:-up}"

if [ "$cmd" = "stop" ]; then
  supabase stop --no-backup || true
  rm -f .env.development.local
  echo "Local stack stopped. dev now reverts to .env.local."
  exit 0
fi

echo "▶ Starting local Supabase (Docker)…"
supabase start >/dev/null 2>&1 || supabase start

# Pull the local stack's URL + keys.
set -a; eval "$(supabase status -o env 2>/dev/null)"; set +a

if [ "$cmd" = "reset" ]; then
  echo "▶ Resetting local DB (re-applying migrations)…"
  supabase db reset >/dev/null
fi

echo "▶ Seeding demo data…"
SEED_ARGS=""
[ "$cmd" = "reset" ] && SEED_ARGS="--force"
SUPABASE_URL="$API_URL" SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY" ANON_KEY="$ANON_KEY" \
  node scripts/seed-demo.mjs $SEED_ARGS

echo "▶ Pointing dev at the local stack (.env.development.local)…"
cat > .env.development.local <<EOF
# Auto-generated by tt-demo — points local dev at the LOCAL Supabase stack.
# Overrides .env.local in development. Run \`tt-demo stop\` to revert.
NEXT_PUBLIC_SUPABASE_URL=$API_URL
NEXT_PUBLIC_SUPABASE_ANON_KEY=$ANON_KEY
EOF

echo ""
echo "✓ Demo ready → http://localhost:3001"
echo "  On /login use the 'Local demo' buttons (host or cleaner)."
echo ""
exec npm run dev -- -p 3001
